version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        gitlab_rails['initial_root_password'] = "password"
        gitlab_rails['store_initial_root_password'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
       # letsencrypt['enable'] = true
       # letsencrypt['contact_emails'] = ['admin@example.com'] # This should be an array of email addresses to add as contacts
       # letsencrypt['auto_renew'] = true
    ports:
      - '8085:80'
      - '8443:443'
      - '2224:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    shm_size: '256m'
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: